=== extenda/hiiretail-json-schema-registry/external-events/grc/grc.public.event.goods-received.v1.json
{
  "$id": "grc.public.event.goods-received.v1",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Publishes Goods Received events",
  "description": "Contains delivery lines submitted by user.",
  "type": "object",
  "required": [
    "tenantId",
    "businessUnitId",
    "uniqueId",
    "deliveryNoteId",
    "shipperType",
    "shipperId",
    "deliveryDate",
    "submittedAt",
    "submittedBy",
    "lines"
  ],
  "additionalProperties": false,
  "properties": {
    "tenantId": {
      "type": "string",
      "description": "Id to indicate the tenant"
    },
    "businessUnitId": {
      "type": "string",
      "description": "Id to indicate the business unit"
    },
    "uniqueId": {
      "type": "string",
      "description": "Unique, internal id to identify the delivery note"
    },
    "deliveryNoteId": {
      "type": "string",
      "description": "External id to identify the delivery note"
    },
    "shipperType": {
      "description": "Shipper Type",
      "type": "string",
      "enum": [
        "businessPartnerId",
        "businessUnitId"
      ]
    },
    "shipperId": {
      "type": "string",
      "description": "Id to indicate the shipper of the delivery"
    },
    "deliveryDate": {
      "type": "string",
      "format": "date-time",
      "description": "Date to indicate the delivery date"
    },
    "submittedAt": {
      "type": "string",
      "format": "date-time",
      "description": "Datetime to indicate when submitted"
    },
    "submittedBy": {
      "type": "string",
      "description": "User id for the user submitted the delivery lines"
    },
    "transportationAmount": {
      "type": ["null", "number"],
      "description": "Amount to indicate the transportation cost"
    },
    "customsAmount": {
      "type": ["null", "number"],
      "description": "Amount to indicate the customs cost"
    },
    "comment": {
      "type": ["null", "string"],
      "description": "Comment for the delivery note"
    },
    "lines": {
      "type": "array",
      "description": "Array to indicate the submitted lines",
      "items": {
        "$ref": "#/$defs/LineDto"
      }
    }
  },
  "$defs": {
    "LineDto": {
      "description": "Line entity used in Transaction",
      "type": "object",
      "required": [
        "lineId",
        "itemId",
        "expectedQuantity",
        "approvedQuantity",
        "deltaQuantity",
        "unitPrice",
        "currencyCode"
      ],
      "additionalProperties": false,
      "properties": {
        "lineId": {
          "type": "string",
          "description": "Unique, internal id to identify the delivery line"
        },
        "itemId": {
          "type": "string",
          "description": "Id to identify the item"
        },
        "orderId": {
          "type": ["null", "string"],
          "description": "Id to indicate the order"
        },
        "orderLineId": {
          "type": ["null", "string"],
          "description": "Id to indicate the order line"
        },
        "expectedQuantity": {
          "type": "number",
          "description": "Quantity delivered according to the delivery note."
        },
        "approvedQuantity": {
          "type": "number",
          "description": "Approved delivered quantity by the business unit."
        },
        "deltaQuantity": {
          "type": "number",
          "description": "Delta between the currently approved quantity, and the approved quantity in previous export if any."
        },
        "unitPrice": {
          "type": ["null", "number"],
          "description": "Amount to indicate the unit price"
        },
        "currencyCode": {
          "type": ["null", "string"],
          "description": "Code to indicate the currency",
          "minLength": 3,
          "maxLength": 3
        },
        "batchNumber": {
          "type": ["null", "string"],
          "description": "The batch number for the delivered items."
        },
        "bestBeforeDate": {
          "type": ["null", "string"],
          "format": "date",
          "description": "Date to indicate the best before date"
        },
        "expirationDate": {
          "type": ["null", "string"],
          "format": "date",
          "description": "Date to indicate the expiration date"
        },
        "reasonCodes": {
          "type": ["null", "array"],
          "description": "Contains an array of reason codes indicating the reason for any quantity not approved",
          "items": {
            "$ref": "#/$defs/ReasonCodesDto"
          }
        },
        "containers": {
          "type": ["null", "array"],
          "description": "Array to indicate the containers",
          "items": {
            "$ref": "#/$defs/ContainerDto"
          }
        },
        "serialNumbers": {
          "type": ["null", "array"],
          "description": "Array to indicate the serial numbers",
          "items": {
            "type": "string",
            "description": "String to indicate the serial number"
          }
        }
      }
    },
    "ReasonCodesDto": {
      "description": "Reason codes for any deviations",
      "type": "object",
      "required": [
        "id",
        "quantity"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "description": "Id to indicate the reason for a deviation"
        },
        "quantity": {
          "type": "number",
          "description": "Quantity/deviation for the related reason code"
        }
      }
    },
    "ContainerDto": {
      "description": "Container entity used in LineDto",
      "type": "object",
      "required": [
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "description": "Id to indicate the container"
        }
      }
    }
  }
}

=== extenda/hiiretail-json-schema-registry/tools/test/fixtures/unpriced-line.json
{
  "businessUnitId": "123456",
  "comment": "comment",
  "customsAmount": 10,
  "deliveryDate": "2026-09-03T05:36:35.234000000Z",
  "deliveryNoteId": "84eee99a-9af9-4f62-af63-8e2990bbef41",
  "shipperId": "0489ae8b-7281-4aab-b7e5-efd9091d149f",
  "shipperType": "businessPartnerId",
  "submittedAt": "2026-09-03T05:36:35.318Z",
  "submittedBy": "userId",
  "tenantId": "tenantId",
  "transportationAmount": 10,
  "uniqueId": "cf4f7ab7-da28-48bb-920d-25f6a7f9ab25",
  "lines": [
    {
      "approvedQuantity": 10,
      "deltaQuantity": 10,
      "expectedQuantity": 10,
      "batchNumber": null,
      "containers": [],
      "currencyCode": null,
      "itemId": "c6617439-9874-4ffe-acb3-2e305042b6eb",
      "lineId": "1",
      "orderId": "70c8ff7f-a49e-4cf0-9f8d-680fd706f1ba",
      "orderLineId": null,
      "reasonCodes": [],
      "serialNumbers": null,
      "unitPrice": null
    }
  ]
}

=== extenda/hiiretail-json-schema-registry/tools/test/fixtures/priced-line.json
{
  "businessUnitId": "123456",
  "comment": "comment",
  "customsAmount": 10,
  "deliveryDate": "2026-09-03T05:36:34.595000000Z",
  "deliveryNoteId": "d629e49d-a04a-41b7-84ea-e8540c3d5f96",
  "shipperId": "f4481ed3-003d-4faa-999d-cda54460be0c",
  "shipperType": "businessPartnerId",
  "submittedAt": "2026-09-03T05:36:34.880Z",
  "submittedBy": "userId",
  "tenantId": "tenantId",
  "transportationAmount": 10,
  "uniqueId": "3c6f9f4f-f30d-4fdd-ba0b-b628f9fdf06b",
  "lines": [
    {
      "approvedQuantity": 10,
      "deltaQuantity": 10,
      "expectedQuantity": 10,
      "batchNumber": null,
      "bestBeforeDate": "2024-11-01",
      "containers": [],
      "currencyCode": "EUR",
      "expirationDate": "2024-11-01",
      "itemId": "d3fcf18f-a09a-47f3-9b0c-0c934b52980e",
      "lineId": "1",
      "orderId": "12ea3013-e075-433b-a603-d24023bfedc3",
      "orderLineId": null,
      "reasonCodes": [],
      "serialNumbers": null,
      "unitPrice": 10
    }
  ]
}
